apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: default
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:                     # Add a selector to match the labels
    matchLabels:
      app: simple-app
  template:
    metadata:                   # Ensure the labels in the template match the selector
      labels:
        app: simple-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: simple-app      # Match the ConfigMap name
